package org.pragmaticminds.crunch.execution;

import org.pragmaticminds.crunch.events.Event;

/**
 * Callback Interface to be used in conjunction with {@link CrunchExecutor}.
 *
 * @author julian
 * Created by julian on 15.08.18
 */
@FunctionalInterface
public interface EventSink {

    /**
     * Is called by the pipeline whenever a new Event is received.
     *
     * @param event Event that is generated by the pipeline
     */
    void handle(Event event);

}
